# 버전을 지정
version: '3.8'

# 서비스 정의
services:
  # mairadb 서비스
  mariadb:
    restart: always
    # Dockerfile 위치
    build: requirements/mariadb
    container_name: mariadb
    # 베이스 이미지
    image: mariadb
    # 호스트 머신에 대한 포트를 공개하지 않고 링크 기능을 사용하여 연결하는 컨테이너에게만 포트
    expose:
      - "3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - intra-network
    env_file:
      - .env

  # wordpress 서비스
  wordpress:
    # wordpress 컨테이너 시작 전에 mariadb 컨테이너 시작
    depends_on:
      - mariadb
    restart: always
    # Dockerfile 위치
    build: requirements/wordpress
    container_name: wordpress
    # 베이스 이미지
    image: wordpress
    # 호스트 머신에 대한 포트를 공개하지 않고 링크 기능을 사용하여 연결하는 컨테이너에게만 포트
    expose:
      - "9000"
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    networks:
      - intra-network
    env_file:
      - .env
  # nginx 서비스
  nginx:
    # nginx 컨테이너 시작 전에 wordpress 컨테이너 시작
    depends_on:
      - wordpress
    restart: always
    # Dockerfile 위치
    build: requirements/nginx
    container_name: nginx
    # 베이스 이미지
    image: nginx
    # 컨테이너가 공개하는 포트
    ports:
      - "443:443" # "호스트 머신의 포트 번호:컨테이너의 포트 번호"
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    networks:
      - intra-network
    env_file:
      - .env

# 네트워크 정의
networks:
  intra-network:
    driver: bridge
    name: intra-network

# 데이터 볼륨 정의
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gyumpark/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gyumpark/data/wordpress
